package runtime

import (
	"context"
	"crypto/sha256"
	"fmt"
	"strings"
	"time"

	"github.com/supermonkeyguys/specship/apps/server-go/internal/domain"
	"github.com/supermonkeyguys/specship/apps/server-go/internal/infra/toolrunner"
)

type StubExecutor struct {
	ToolRunner toolrunner.Client
}

func NewStubExecutor() *StubExecutor {
	return &StubExecutor{}
}

func NewDeterministicExecutor(runner toolrunner.Client) *StubExecutor {
	return &StubExecutor{ToolRunner: runner}
}

func (e *StubExecutor) ExecuteNode(ctx context.Context, g *domain.Graph, node *domain.Node) (*ExecutionResult, error) {
	_ = g
	started := time.Now().UTC()

	filesWritten := make([]domain.FileRecord, 0, len(node.Outputs))
	toolCalls := make([]domain.ToolCall, 0, len(node.Outputs))
	for _, output := range node.Outputs {
		content := deterministicContentFor(node, output)
		if e.ToolRunner != nil {
			resp, err := e.ToolRunner.WriteFile(ctx, toolrunner.WriteFileRequest{
				RelativePath:  output,
				Content:       content,
				AllowedWrites: node.Outputs,
			})
			if err != nil {
				return nil, err
			}
			toolCalls = append(toolCalls, domain.ToolCall{
				Tool:      "write_file",
				InputJSON: fmt.Sprintf(`{"path":%q}`, output),
				Output:    resp.Output,
				Success:   resp.Success,
				At:        time.Now().UTC(),
			})
		}
		sum := sha256.Sum256([]byte(content))
		filesWritten = append(filesWritten, domain.FileRecord{
			Path:      output,
			Operation: "create",
			SizeBytes: int64(len(content)),
			Checksum:  fmt.Sprintf("%x", sum)[:16],
			At:        time.Now().UTC(),
		})
	}

	completed := time.Now().UTC()
	evidence := &domain.Evidence{
		ModelUsed:     "deterministic-executor",
		ToolCalls:     toolCalls,
		FilesWritten:  filesWritten,
		Verifications: []domain.VerificationRecord{},
		StartedAt:     started,
		CompletedAt:   &completed,
		DurationMs:    completed.Sub(started).Milliseconds(),
	}
	return &ExecutionResult{Evidence: evidence}, nil
}

func deterministicContentFor(node *domain.Node, output string) string {
	spec := strings.TrimSpace(node.Task)
	title := strings.TrimSpace(node.Title)
	if title == "" {
		title = "Shipyard Output"
	}
	escapedTitle := htmlEscape(title)
	escapedSpec := htmlEscape(spec)
	switch strings.ToLower(output) {
	case "output/index.html":
		return "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>" + escapedTitle + "</title>\n    <style>body{font-family:system-ui,-apple-system,sans-serif;margin:0;padding:32px;background:#f8fafc;color:#0f172a}main{max-width:720px;margin:0 auto;background:white;border:1px solid #e2e8f0;border-radius:16px;padding:24px;box-shadow:0 10px 30px rgba(15,23,42,.08)}h1{margin-top:0}ul{padding-left:20px}</style>\n  </head>\n  <body>\n    <main>\n      <h1>" + escapedTitle + "</h1>\n      <p>This static prototype was generated by the default server-go deterministic executor.</p>\n      <section>\n        <h2>Requested task</h2>\n        <p>" + escapedSpec + "</p>\n      </section>\n      <section>\n        <h2>What to do next</h2>\n        <ul>\n          <li>Connect a real LLM planner/executor for richer output.</li>\n          <li>Extend preview/live runtime when moving toward replacement readiness.</li>\n          <li>Use this path as the default no-LLM successful smoke target.</li>\n        </ul>\n      </section>\n    </main>\n  </body>\n</html>\n"
	default:
		return "Generated output for: " + spec + "\n"
	}
}

func htmlEscape(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&#39;",
	)
	return replacer.Replace(s)
}
